title: "SCP:IC Wiki"
author: "Lappland"
avatar: "/SCP-IC/IC.png"
round-avatar: true
title-on-all-pages: true
icon: BETA_WIKI.png
favicon: "/SCP-IC/IC.png"
post_search: true
edit_page_button: true
description: "Intelligent Cat SCP Wiki"
show_downloads: False
google_analytics: G-1344DZ4TJK
remote_theme: pages-themes/hacker@v0.2.0
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-remote-theme
