name: Check Secrets

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to check'
        required: true
        default: ''
      password:
        description: 'Password to check'
        required: true
        default: ''

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check username and password
        run: |
          echo "::set-output name=USERNAME::${{ github.event.inputs.username }}"
          echo "::set-output name=PASSWORD::${{ github.event.inputs.password }}"
          python check_secrets.py
        env:
          USERNAME1: ${{ secrets.USERNAME1 }}
          USERNAME2: ${{ secrets.USERNAME2 }}
          USERNAME3: ${{ secrets.USERNAME3 }}
        id: check

      - name: Output result
        run: echo "${{ steps.check.outputs.result }}"
